# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

# gem "rails"
gem "allure-cucumber"
gem "capybara"
gem "cucumber"
gem "faker"
gem "nokogiri"
gem "pry"
gem "rspec"
gem "selenium-webdriver"
gem "site_prism"
gem "mysql2"