# frozen_string_literal: true

source "https://rubygems.org"

gem 'allure-cucumber'
gem "capybara"
gem "cucumber"
gem "parallel_tests"
gem "pry"
gem "rspec"
gem "selenium-webdriver"
gem "site_prism"
gem 'ffi'
